basePath: /task
definitions:
  response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  save.Request:
    properties:
      description:
        description: 'example: This is a sample task description.'
        type: string
      parent_task_id:
        description: 'example: b063de04-6fd7-41cd-8f4c-8d113e786be8'
        type: string
      repeat_task:
        description: |-
          enum: DAILY, WEEKLY, MONTHLY, YEARLY, NEVER
          example: DAILY
        type: string
      title:
        description: 'example: Sample Task'
        example: Sample Task
        type: string
      user_id:
        description: |-
          required: true
          example: b063de04-6fd7-41cd-8f4c-8d113e786be8
        type: string
    required:
    - user_id
    type: object
  save.Response:
    properties:
      error:
        type: string
      status:
        type: string
      task_id:
        description: 'example: b063de04-6fd7-41cd-8f4c-8d113e786be8'
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample task service API.
  title: Task service API
  version: "1.0"
paths:
  /task:
    post:
      consumes:
      - application/json
      description: Create and save task
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/save.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Task created successfully
          schema:
            $ref: '#/definitions/save.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Failed to save task
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create task
      tags:
      - Task
swagger: "2.0"
