version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    ports:
      - "6432:5432"
    restart: unless-stopped

  http-server:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./task-service/config/local.yaml:/app/config/local.yaml
    environment:
      - CONFIG_PATH=/app/config/local.yaml
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped