environment: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: 6432
  user: "postgres"
  password: "postgres"
  name: "task_manager"
  sslmode: "disable"
redis:
  host: "localhost"
  port: 6379
  user: "user"
  password: ""
  db: 1
  max_retries: 4
  dial_timeout: 5s