environment: "local"
http_server:
  address: "localhost:7654"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: 6432
  user: "postgres"
  password: "postgres"
  name: "task_manager"
  sslmode: "disable"